# Generated by Django 5.2.4 on 2026-03-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_about_alter_customuser_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Форматы: 8XXXXXXXXXX, либо +7XXXXXXXXXX', max_length=12, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
